### ISSUE TITLE
Pre-trained models and codes for hallucination critic

### ISSUE THREAD

**Issue by sjpark9503** [nouhadziri/Neural-Path-Hunter#2]
Hi, thank you for valuable and interesting work.

I'd like to implement the hallucination critic you developed, where can I find the code for this?
Also, I wonder if you are planning to release a pre-trained model of hallucination critic.

**Comment by nouhadziri** [comment]
Hi @sjpark9503,  thanks for your interest in our work and apologies for the delayed reply. We have uploaded the critic pre-trained model and also the code for training it. Please let us know if you encounter any issues. Thanks.
