### ISSUE TITLE
How do you get the graph embeddings?

### ISSUE THREAD

**Issue by ziweiji** [nouhadziri/Neural-Path-Hunter#3]
Thanks for your amazing work! I am confused about the graph embeddings you share. 
Is it "KG-Entity Memory" in your paper? Or do you get it from other places? 
If you train them, could you share the code?

**Comment by nouhadziri** [comment]
Hi @ziweiji, thanks for your interest in our work and apologies for the delayed reply. 
Yes, the graph embedding we share is the one we use for KG-Entity Memory. You can get the graph embedding from here: https://drive.google.com/drive/folders/1KzjCq0-8K1pqi1TFfsEC3iKiaK-2oL1I
